# [en]
#   languageName = "English"
#   weight = 1

# [fr]
#   languageName = "Français"
#   weight = 2
#   [fr.params]
#     dateFormat = "02-01-2006"
#     description = "Un thème de blog extrêmement rapide, réactif et riche en fonctionnalités pour Hugo"
#     keywords = "Hugo, Bootstrap, Thème Blog"

[zh-cn]
  languageName = "简体中文"
  weight = 1
  [zh-cn.params]
    dateFormat = "2006-01-02"
    description = "每一天都奔走在自己的热爱里."
    keywords = "Hugo, Bootstrap, 博客主题"
    [zh-cn.params.archive]
      dateFormat = "01-02"
