[[main]]
  name = "友情链接"
  identifier = "friends"
  weight = 40
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  name = "xieash"
  identifier = "xieash"
  parent = "friends"
  url = "https://xieash.work/"
  weight = 1
[[main]]
  name = "sunnysab"
  identifier = "sunnysab"
  parent = "friends"
  url = "https://sunnysab.cn/"
  weight = 2
[[main]]
  name = "wanfengcxz"
  identifier = "wanfengcxz"
  parent = "friends"
  url = "https://wanfengcxz.cn/"
  weight = 3
[[main]]
  name = "zhangzqs"
  identifier = "zhangzqs"
  parent = "friends"
  url = "https://zhangzqs.cn/"
  weight = 4

[[main]]
  name = "资料"
  identifier = "data"
  weight = 40
  url = "data"
#   pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
# [[footer]]
#   name = "Support"
#   identifier = "support"
#   weight = 1
# [[footer]]
#   name = "Repository"
#   identifier = "repository"
#   parent = "support"
#   url = "https://github.com/razonyang/hugo-theme-bootstrap"
#   weight = 1
#   pre = '<i class="fab fa-fw fa-github"></i>'
# [[footer]]
#   name = "Discussions"
#   identifier = "discussions"
#   parent = "support"
#   url = "https://github.com/razonyang/hugo-theme-bootstrap/discussions/new"
#   weight = 2
#   pre = '<i class="fas fa-fw fa-comments"></i>'
# [[footer]]
#   name = "Features Request"
#   identifier = "feature-request"
#   parent = "support"
#   url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=feature_request.md"
#   weight = 3
# [[footer]]
#   name = "Bug Report"
#   identifier = "bug-report"
#   parent = "support"
#   url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=bug_report.md"
#   weight = 4

# [[footer]]
#   name = "Docs"
#   identifier = "docs"
#   weight = 2

# [[footer]]
#   name = "Features"
#   identifier = "features"
#   weight = 3

# [[footer]]
#   identifier = "demo"
#   name = "Demo"
#   weight = 4
# [[footer]]
#   identifier = "demo-netlify"
#   parent = "demo"
#   name = "Netlify"
#   weight = 1
#   url = "https://hbs.razonyang.com"
# [[footer]]
#   identifier = "demo-china"
#   parent = "demo"
#   name = "China"
#   weight = 2
#   url = "https://hbs-cn.razonyang.com"
